const stateData = {
    bow: false,
    boomerang: false,
    hookshot: false,
    bomb: false,
    powder: false,
    mushroom: false,
    firerod: false,
    icerod: false,
    bombos: false,
    ether: false,
    quake: false,
    shovel: false,
    lantern: false,
    hammer: false,
    flute: false,
    net: false,
    book: false,
    moonPearl: false,
    bottle: false,
    somaria: false,
    byrna: false,
    cape: false,
    mirror: false,
    gloves: false,
    boots: false,
    flippers: false,
    magic: false,
    sword: false,
    shield: false,
    tunic: false,
    EP: false,
    DP: false,
    TH: false,
    PD: false,
    SP: false,
    SW: false,
    TT: false,
    IP: false,
    MM: false,
    TR: false,
    gomode: false,
    agahnim: false,
    crystal: false
}

export default stateData;